-- Database Schema Part 2 (Missing Tables & Dummy Data)

-- 7. Manzara (Sosyal Akış - Fotoğraf Paylaşımları)
CREATE TABLE posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id),
  image_url TEXT NOT NULL,
  caption TEXT,
  location_name TEXT,
  likes_count INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 8. Pazaryeri (İkinci El İlanlar)
CREATE TABLE marketplace_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id),
  title TEXT NOT NULL,
  description TEXT,
  category TEXT NOT NULL,
  price DECIMAL NOT NULL,
  currency TEXT DEFAULT '₺',
  image_url TEXT,
  location_name TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- RLS Disable for easy testing
ALTER TABLE posts DISABLE ROW LEVEL SECURITY;
ALTER TABLE marketplace_items DISABLE ROW LEVEL SECURITY;

-- Insert Dummy Data for Pazaryeri
INSERT INTO marketplace_items (title, description, category, price, image_url, location_name)
VALUES 
('100W Güneş Paneli', 'Sadece 2 ay kullanıldı, sıfır gibi.', 'Elektronik', 1500, 'https://images.unsplash.com/photo-1509391366360-2e959784a276?q=80&w=400&auto=format&fit=crop', 'İzmir'),
('Tente 3x2.5m', 'Karavan tentesi, mekanizması sağlam.', 'Dış Donanım', 3200, 'https://images.unsplash.com/photo-1523987355523-c7b5b0dd90a7?q=80&w=400&auto=format&fit=crop', 'Antalya'),
('Portatif Tuvalet', 'Temiz kullanıldı, kimyasalları ile birlikte.', 'İç Donanım', 800, 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?q=80&w=400&auto=format&fit=crop', 'İstanbul');

-- Insert Dummy Data for Manzara (Posts)
INSERT INTO posts (image_url, caption, location_name, likes_count)
VALUES 
('https://images.unsplash.com/photo-1523987355523-c7b5b0dd90a7?q=80&w=800&auto=format&fit=crop', 'Sabah kahvesi eşliğinde güneşe uyanmak... 🌲☕️', 'Yedigöller, Bolu', 24),
('https://images.unsplash.com/photo-1513311068348-19c8fbdc0bb6?q=80&w=800&auto=format&fit=crop', 'Yollar bizi çağırıyor. Sıradaki durak neresi olsun? 🚐', 'Kaş, Antalya', 56),
('https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?q=80&w=800&auto=format&fit=crop', 'Akşam yemeği hazırlıkları başladı. Odun ateşi bir başka.', 'Kaz Dağları', 12);

-- View for easy Map fetching
CREATE VIEW vw_spots AS
SELECT 
  id, title, description, category, address, 
  ST_Y(location::geometry) as lat, 
  ST_X(location::geometry) as lng 
FROM spots;

-- Insert Dummy Spot
INSERT INTO spots (title, category, location, address) 
VALUES ('Zeytinli Bahçe', 'Sakin Köşe', ST_GeographyFromText('POINT(26.5 39.5)'), 'Çanakkale, Ayvacık');

