-- =====================================================================
-- v8 — UI Bileşenleri için eksik şema (Antigravity sonrası)
-- - seasonal_tips (rehber + SeasonalTips bileşeni)
-- - activities (ActivityFeed bileşeni, canlı yol durumu)
-- - profiles.current_status, profiles.is_verified (Telsiz, Profil)
-- Idempotent — birden fazla kez çalıştırılabilir.
-- =====================================================================

-- ---- 1. profiles için yeni kolonlar ----
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                 WHERE table_name='profiles' AND column_name='current_status') THEN
    ALTER TABLE profiles ADD COLUMN current_status TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                 WHERE table_name='profiles' AND column_name='is_verified') THEN
    ALTER TABLE profiles ADD COLUMN is_verified BOOLEAN DEFAULT false;
  END IF;
END $$;

-- ---- 2. seasonal_tips ----
CREATE TABLE IF NOT EXISTS seasonal_tips (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  month SMALLINT NOT NULL CHECK (month BETWEEN 1 AND 12),
  category TEXT NOT NULL,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE seasonal_tips DISABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON seasonal_tips TO anon, authenticated;

-- Tohum data (yalnızca tablo boşsa)
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM seasonal_tips LIMIT 1) THEN
    INSERT INTO seasonal_tips (month, category, title, content) VALUES
      (5, 'Teknik',  'Su Deposu Temizliği',  'Yaz sezonu başlamadan önce su depolarınızı gümüş iyonlu tabletlerle dezenfekte edin.'),
      (5, 'Rota',    'Batı Karadeniz Zamanı','Mayıs ayı, Batı Karadeniz ormanlarının en yeşil olduğu dönemdir. Yedigöller ve Akçakoca rotalarını değerlendirin.'),
      (5, 'Ekipman', 'Sineklik Kontrolü',    'Havaların ısınmasıyla artan haşerelere karşı tüm sinekliklerinizi kontrol edin.'),
      (6, 'Enerji',  'Panel Isınması',       'Paneller çok ısındığında verim düşer. Altındaki hava boşluğunun açık olduğundan emin olun.'),
      (6, 'Kamp',    'Gölge Stratejisi',     'Yazın konaklarken karavanın kapısının kuzeye bakması, gün boyu gölge sağlar.'),
      (7, 'Güvenlik','Yangın Riski',         'Orman yangını riskinin zirvede olduğu ay; ateş yakmaktan ve sigarayı dışarı atmaktan kaçının.'),
      (7, 'Su',      'İçme Suyu Stoku',      'Sıcakta günlük su tüketimi 4-5 L/kişi olur. Yola çıkmadan tankları doldurun.'),
      (8, 'Kalabalık','Sahil Yoğunluğu',     'Ağustos sahil yoğunluğu zirvede. İç Anadolu/yayla rotaları daha sakin.'),
      (9, 'Rota',    'Sonbahar Yaylaları',   'Eylül, Karadeniz ve Doğu yaylaları için en uygun ay — yağmur az, hava ılıman.'),
      (10,'Bakım',   'Kış Hazırlığı',        'Lastik basıncı, akü voltajı ve antifriz seviyesini kontrol edin.'),
      (11,'Donma',   'Su Hattı Boşaltma',    'İlk donlardan önce kullanılmayan su hatlarını boşaltın, kompresörle kurutun.'),
      (12,'Isınma',  'Webasto Bakımı',       'Dizel ısıtıcının yakıt filtresini ve egzoz çıkışını temizleyin.'),
      (1, 'Donma',   'Gri Su Tahliyesi',     'Don riski olan bölgelerde gri su vananızı açık bırakın veya antifriz kullanın.'),
      (2, 'Kış Kampı','Termal İzolasyon',    'Pencere termal perdeleri %30 ısı kaybını önler.'),
      (3, 'Bakım',   'Bahar Servisi',        'Kış uykusundan çıkan araç için yağ + filtre + lastik dönüşümü zamanı.'),
      (4, 'Rota',    'Çiçek Açan Anadolu',   'Nisan, İç Ege ve Akdeniz hinterlandında kır çiçekleri için en güzel zaman.');
  END IF;
END $$;

-- ---- 3. activities (Canlı Yol Durumu / ActivityFeed) ----
CREATE TABLE IF NOT EXISTS activities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  activity_type TEXT NOT NULL CHECK (activity_type IN ('note','route','post','item','spot','review')),
  description TEXT NOT NULL,
  ref_id BIGINT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE activities DISABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON activities TO anon, authenticated;

-- Realtime publication'a ekle (canlı feed için)
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime' AND tablename = 'activities'
  ) THEN
    EXECUTE 'ALTER PUBLICATION supabase_realtime ADD TABLE activities';
  END IF;
END $$;

-- ---- 4. Otomatik activity tetikleyicileri ----
-- Her yeni post, route, note, marketplace_item için bir activity satırı oluştur

CREATE OR REPLACE FUNCTION fn_log_activity_post() RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO activities (user_id, activity_type, description, ref_id)
  VALUES (NEW.user_id, 'post', 'yeni bir manzara paylaştı: ' || COALESCE(NEW.location_name, 'bilinmeyen konum'), NEW.id);
  RETURN NEW;
END $$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION fn_log_activity_route() RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO activities (user_id, activity_type, description, ref_id)
  VALUES (NEW.user_id, 'route', 'yeni rota bıraktı: ' || NEW.title, NEW.id);
  RETURN NEW;
END $$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION fn_log_activity_note() RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO activities (user_id, activity_type, description, ref_id)
  VALUES (NEW.user_id, 'note', 'askıya not bıraktı: ' || COALESCE(NEW.location_name,''), NEW.id);
  RETURN NEW;
END $$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION fn_log_activity_item() RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO activities (user_id, activity_type, description, ref_id)
  VALUES (NEW.user_id, 'item', 'pazara ilan ekledi: ' || NEW.title, NEW.id);
  RETURN NEW;
END $$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_activity_post  ON posts;
CREATE TRIGGER trg_activity_post  AFTER INSERT ON posts             FOR EACH ROW EXECUTE FUNCTION fn_log_activity_post();
DROP TRIGGER IF EXISTS trg_activity_route ON routes;
CREATE TRIGGER trg_activity_route AFTER INSERT ON routes            FOR EACH ROW EXECUTE FUNCTION fn_log_activity_route();
DROP TRIGGER IF EXISTS trg_activity_note  ON geographic_notes;
CREATE TRIGGER trg_activity_note  AFTER INSERT ON geographic_notes  FOR EACH ROW EXECUTE FUNCTION fn_log_activity_note();
DROP TRIGGER IF EXISTS trg_activity_item  ON marketplace_items;
CREATE TRIGGER trg_activity_item  AFTER INSERT ON marketplace_items FOR EACH ROW EXECUTE FUNCTION fn_log_activity_item();

NOTIFY pgrst, 'reload schema';
