-- =====================================================================
-- v11 — Genişletilmiş XP Aktiviteleri
-- - Yeni aktivite tipleri için XP tanımları
-- - Günlük giriş (Check-in) takibi
-- =====================================================================

-- 1. Günlük Giriş Takibi Tablosu
CREATE TABLE IF NOT EXISTS daily_checkins (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  checkin_date DATE DEFAULT CURRENT_DATE,
  UNIQUE(user_id, checkin_date)
);

-- 2. XP Fonksiyonunu Güncelle (Yeni tipler eklendi)
CREATE OR REPLACE FUNCTION fn_grant_xp() RETURNS TRIGGER AS $$
DECLARE
  xp_to_add INTEGER := 0;
  current_xp INTEGER;
  old_level INTEGER;
  new_level INTEGER;
BEGIN
  -- Activity tipine göre XP belirle
  CASE NEW.activity_type
    WHEN 'post' THEN xp_to_add := 10;
    WHEN 'route' THEN xp_to_add := 25;
    WHEN 'spot' THEN xp_to_add := 30; -- Yeni konaklama noktası ekleme
    WHEN 'review' THEN xp_to_add := 15;
    WHEN 'item' THEN xp_to_add := 5;
    WHEN 'note' THEN 
      IF NEW.description LIKE 'yeni bir etkinlik oluşturdu%' THEN
        xp_to_add := 50;
      ELSIF NEW.description LIKE 'etkinliğe katıldı%' THEN
        xp_to_add := 10;
      ELSIF NEW.description LIKE 'bir görevi tamamladı%' THEN
        -- Görev ödülünü dinamik çek (basitleştirmek için sabit 100 verelim veya challenge_id ref_id ise oradan çekebiliriz)
        xp_to_add := 100; 
      ELSIF NEW.description = 'günlük giriş ödülü' THEN
        xp_to_add := 5;
      ELSE
        xp_to_add := 5;
      END IF;
    ELSE xp_to_add := 0;
  END CASE;

  -- XP'yi güncelle
  UPDATE profiles SET xp = COALESCE(xp, 0) + xp_to_add WHERE id = NEW.user_id 
  RETURNING xp INTO current_xp;

  -- Seviye atlama kontrolü (Her 100 XP bir seviye)
  old_level := (current_xp - xp_to_add) / 100 + 1;
  new_level := current_xp / 100 + 1;

  IF new_level > old_level THEN
    INSERT INTO activities (user_id, activity_type, description)
    VALUES (NEW.user_id, 'note', 'seviye atladı! Yeni Seviye: ' || new_level);
  END IF;

  RETURN NEW;
END $$ LANGUAGE plpgsql;

-- 3. Etkinliğe katılma için aktivite logu
CREATE OR REPLACE FUNCTION fn_log_activity_event_join() RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO activities (user_id, activity_type, description, ref_id)
  VALUES (NEW.user_id, 'note', 'bir etkinliğe katıldı!', NEW.event_id);
  RETURN NEW;
END $$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_activity_event_join ON event_attendees;
CREATE TRIGGER trg_activity_event_join AFTER INSERT ON event_attendees FOR EACH ROW EXECUTE FUNCTION fn_log_activity_event_join();

-- 4. Yeni Spot (Nokta) ekleme için aktivite logu
CREATE OR REPLACE FUNCTION fn_log_activity_spot() RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO activities (user_id, activity_type, description, ref_id)
  VALUES (NEW.created_by, 'spot', 'yeni bir sakin köşe ekledi: ' || NEW.title, NEW.id);
  RETURN NEW;
END $$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_activity_spot ON spots;
CREATE TRIGGER trg_activity_spot AFTER INSERT ON spots FOR EACH ROW EXECUTE FUNCTION fn_log_activity_spot();

-- 5. Günlük Giriş için Stored Procedure (Frontend'den çağrılacak)
CREATE OR REPLACE FUNCTION check_in_user(p_user_id UUID) RETURNS VOID AS $$
BEGIN
  INSERT INTO daily_checkins (user_id, checkin_date)
  VALUES (p_user_id, CURRENT_DATE)
  ON CONFLICT (user_id, checkin_date) DO NOTHING;
  
  IF FOUND THEN
    INSERT INTO activities (user_id, activity_type, description)
    VALUES (p_user_id, 'note', 'günlük giriş ödülü');
  END IF;
END;
$$ LANGUAGE plpgsql;

NOTIFY pgrst, 'reload schema';
