-- =====================================================================
-- Karavan Komşusu — Tek Dosya Idempotent Setup
-- Bu dosyayı tek seferde çalıştır; daha önce ne yüklenmiş ne yüklenmemiş
-- önemli değil. IF NOT EXISTS / DO blokları her şeyi güvenle uygular.
--
-- v1 + v2 + v3 + v4 + v4_fix + v5 + v6 + v8 = TEK DOSYA
-- (v7_rls production'a geçerken ayrıca koşulur)
-- =====================================================================

CREATE EXTENSION IF NOT EXISTS postgis;

-- ---- 1. profiles ----
CREATE TABLE IF NOT EXISTS profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  username TEXT UNIQUE,
  full_name TEXT,
  avatar_url TEXT,
  caravan_type TEXT,
  bio TEXT,
  location_visible BOOLEAN DEFAULT true,
  last_location GEOGRAPHY(POINT),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- profiles ek kolonlar (v5 + v8)
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='profiles' AND column_name='battery_capacity') THEN
    ALTER TABLE profiles ADD COLUMN battery_capacity TEXT;
    ALTER TABLE profiles ADD COLUMN solar_panel TEXT;
    ALTER TABLE profiles ADD COLUMN water_tank TEXT;
    ALTER TABLE profiles ADD COLUMN heating_system TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='profiles' AND column_name='current_status') THEN
    ALTER TABLE profiles ADD COLUMN current_status TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='profiles' AND column_name='is_verified') THEN
    ALTER TABLE profiles ADD COLUMN is_verified BOOLEAN DEFAULT false;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='profiles' AND column_name='caravan_type') THEN
    ALTER TABLE profiles ADD COLUMN caravan_type TEXT;
  END IF;
END $$;

-- profiles auto-create trigger (signup sonrası)
CREATE OR REPLACE FUNCTION public.handle_new_user() RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name)
  VALUES (NEW.id, COALESCE(NEW.raw_user_meta_data->>'full_name', NEW.email))
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ---- 2. spots ----
CREATE TABLE IF NOT EXISTS spots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_by UUID REFERENCES profiles(id),
  title TEXT NOT NULL,
  description TEXT,
  category TEXT,
  location GEOGRAPHY(POINT) NOT NULL,
  address TEXT,
  features JSONB,
  images TEXT[],
  is_verified BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='spots' AND column_name='created_by') THEN
    ALTER TABLE spots ADD COLUMN created_by UUID REFERENCES profiles(id);
  END IF;
END $$;

-- ---- 3. service_providers ----
CREATE TABLE IF NOT EXISTS service_providers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  category TEXT NOT NULL,
  phone TEXT,
  whatsapp TEXT,
  address TEXT,
  location GEOGRAPHY(POINT),
  images TEXT[],
  rating DECIMAL DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ---- 4. reviews ----
CREATE TABLE IF NOT EXISTS reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES profiles(id),
  spot_id BIGINT REFERENCES spots(id),
  service_id BIGINT REFERENCES service_providers(id),
  rating INTEGER CHECK (rating >= 1 AND rating <= 5),
  comment TEXT,
  images TEXT[],
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ---- 5. friendships ----
CREATE TABLE IF NOT EXISTS friendships (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id),
  friend_id UUID REFERENCES auth.users(id),
  status TEXT DEFAULT 'accepted',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(user_id, friend_id)
);

-- ---- 6. posts ----
CREATE TABLE IF NOT EXISTS posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  image_url TEXT NOT NULL,
  caption TEXT,
  location_name TEXT,
  likes_count INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ---- 7. marketplace_items ----
CREATE TABLE IF NOT EXISTS marketplace_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT,
  category TEXT NOT NULL,
  price DECIMAL NOT NULL,
  currency TEXT DEFAULT '₺',
  image_url TEXT,
  location_name TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ---- 8. messages (Telsiz) ----
CREATE TABLE IF NOT EXISTS messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  channel TEXT NOT NULL,
  text TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ---- 9. geographic_notes (Askıda Not) ----
CREATE TABLE IF NOT EXISTS geographic_notes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  note TEXT NOT NULL,
  location GEOGRAPHY(POINT) NOT NULL,
  location_name TEXT,
  expires_at TIMESTAMP WITH TIME ZONE DEFAULT (now() + interval '7 days'),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ---- 10. routes (İz Bırak) ----
CREATE TABLE IF NOT EXISTS routes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT,
  path GEOGRAPHY(LINESTRING) NOT NULL,
  start_location_name TEXT,
  end_location_name TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ---- 11. comments ----
CREATE TABLE IF NOT EXISTS comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id BIGINT REFERENCES posts(id) ON DELETE CASCADE,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  comment TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ---- 12. bookmarks ----
CREATE TABLE IF NOT EXISTS bookmarks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  item_type TEXT NOT NULL,
  item_id BIGINT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(user_id, item_type, item_id)
);

-- ---- 13. seasonal_tips ----
CREATE TABLE IF NOT EXISTS seasonal_tips (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  month SMALLINT NOT NULL CHECK (month BETWEEN 1 AND 12),
  category TEXT NOT NULL,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ---- 14. activities ----
CREATE TABLE IF NOT EXISTS activities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  activity_type TEXT NOT NULL CHECK (activity_type IN ('note','route','post','item','spot','review')),
  description TEXT NOT NULL,
  ref_id BIGINT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- =====================================================================
-- View'lar
-- =====================================================================
CREATE OR REPLACE VIEW vw_spots AS
SELECT id, title, description, category, address,
       ST_Y(location::geometry) as lat,
       ST_X(location::geometry) as lng
FROM spots;

CREATE OR REPLACE VIEW vw_geographic_notes AS
SELECT id, user_id, note, location_name, created_at,
       ST_Y(location::geometry) as lat,
       ST_X(location::geometry) as lng
FROM geographic_notes;

CREATE OR REPLACE VIEW vw_routes AS
SELECT id, user_id, title, description, start_location_name, end_location_name, created_at,
       ST_AsGeoJSON(path)::json as geojson_path
FROM routes;

-- =====================================================================
-- DEV: RLS kapat (production için v7_rls.sql çalıştır)
-- =====================================================================
DO $$ BEGIN
  EXECUTE 'ALTER TABLE profiles          DISABLE ROW LEVEL SECURITY';
  EXECUTE 'ALTER TABLE spots             DISABLE ROW LEVEL SECURITY';
  EXECUTE 'ALTER TABLE service_providers DISABLE ROW LEVEL SECURITY';
  EXECUTE 'ALTER TABLE reviews           DISABLE ROW LEVEL SECURITY';
  EXECUTE 'ALTER TABLE friendships       DISABLE ROW LEVEL SECURITY';
  EXECUTE 'ALTER TABLE posts             DISABLE ROW LEVEL SECURITY';
  EXECUTE 'ALTER TABLE marketplace_items DISABLE ROW LEVEL SECURITY';
  EXECUTE 'ALTER TABLE messages          DISABLE ROW LEVEL SECURITY';
  EXECUTE 'ALTER TABLE geographic_notes  DISABLE ROW LEVEL SECURITY';
  EXECUTE 'ALTER TABLE routes            DISABLE ROW LEVEL SECURITY';
  EXECUTE 'ALTER TABLE comments          DISABLE ROW LEVEL SECURITY';
  EXECUTE 'ALTER TABLE bookmarks         DISABLE ROW LEVEL SECURITY';
  EXECUTE 'ALTER TABLE seasonal_tips     DISABLE ROW LEVEL SECURITY';
  EXECUTE 'ALTER TABLE activities        DISABLE ROW LEVEL SECURITY';
END $$;

-- Grant'ler
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO anon, authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;

-- Realtime publication (messages + activities)
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname='supabase_realtime' AND tablename='messages') THEN
    EXECUTE 'ALTER PUBLICATION supabase_realtime ADD TABLE messages';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname='supabase_realtime' AND tablename='activities') THEN
    EXECUTE 'ALTER PUBLICATION supabase_realtime ADD TABLE activities';
  END IF;
END $$;

-- =====================================================================
-- Activity tetikleyicileri
-- =====================================================================
CREATE OR REPLACE FUNCTION fn_log_activity_post() RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO activities (user_id, activity_type, description, ref_id)
  VALUES (NEW.user_id, 'post', 'yeni bir manzara paylaştı: ' || COALESCE(NEW.location_name, ''), NEW.id);
  RETURN NEW;
END $$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION fn_log_activity_route() RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO activities (user_id, activity_type, description, ref_id)
  VALUES (NEW.user_id, 'route', 'yeni rota bıraktı: ' || NEW.title, NEW.id);
  RETURN NEW;
END $$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION fn_log_activity_note() RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO activities (user_id, activity_type, description, ref_id)
  VALUES (NEW.user_id, 'note', 'askıya not bıraktı: ' || COALESCE(NEW.location_name,''), NEW.id);
  RETURN NEW;
END $$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION fn_log_activity_item() RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO activities (user_id, activity_type, description, ref_id)
  VALUES (NEW.user_id, 'item', 'pazara ilan ekledi: ' || NEW.title, NEW.id);
  RETURN NEW;
END $$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_activity_post  ON posts;
CREATE TRIGGER trg_activity_post  AFTER INSERT ON posts             FOR EACH ROW EXECUTE FUNCTION fn_log_activity_post();
DROP TRIGGER IF EXISTS trg_activity_route ON routes;
CREATE TRIGGER trg_activity_route AFTER INSERT ON routes            FOR EACH ROW EXECUTE FUNCTION fn_log_activity_route();
DROP TRIGGER IF EXISTS trg_activity_note  ON geographic_notes;
CREATE TRIGGER trg_activity_note  AFTER INSERT ON geographic_notes  FOR EACH ROW EXECUTE FUNCTION fn_log_activity_note();
DROP TRIGGER IF EXISTS trg_activity_item  ON marketplace_items;
CREATE TRIGGER trg_activity_item  AFTER INSERT ON marketplace_items FOR EACH ROW EXECUTE FUNCTION fn_log_activity_item();

-- =====================================================================
-- Örnek veri (yalnızca tablolar boşsa)
-- =====================================================================
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM marketplace_items LIMIT 1) THEN
    INSERT INTO marketplace_items (title, description, category, price, image_url, location_name) VALUES
      ('100W Güneş Paneli', 'Sadece 2 ay kullanıldı, sıfır gibi.', 'Enerji & Elektrik', 1500, 'https://images.unsplash.com/photo-1509391366360-2e959784a276?q=80&w=400&auto=format&fit=crop', 'İzmir'),
      ('Tente 3x2.5m', 'Karavan tentesi, mekanizması sağlam.', 'Dış Donanım', 3200, 'https://images.unsplash.com/photo-1523987355523-c7b5b0dd90a7?q=80&w=400&auto=format&fit=crop', 'Antalya'),
      ('Portatif Tuvalet', 'Temiz kullanıldı, kimyasalları ile birlikte.', 'İç Donanım', 800, 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?q=80&w=400&auto=format&fit=crop', 'İstanbul');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM posts LIMIT 1) THEN
    INSERT INTO posts (image_url, caption, location_name, likes_count) VALUES
      ('https://images.unsplash.com/photo-1523987355523-c7b5b0dd90a7?q=80&w=800&auto=format&fit=crop', 'Sabah kahvesi eşliğinde güneşe uyanmak... 🌲☕️', 'Yedigöller, Bolu', 24),
      ('https://images.unsplash.com/photo-1513311068348-19c8fbdc0bb6?q=80&w=800&auto=format&fit=crop', 'Yollar bizi çağırıyor. Sıradaki durak neresi olsun? 🚐', 'Kaş, Antalya', 56),
      ('https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?q=80&w=800&auto=format&fit=crop', 'Akşam yemeği hazırlıkları başladı. Odun ateşi bir başka.', 'Kaz Dağları', 12);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM spots LIMIT 1) THEN
    INSERT INTO spots (title, category, location, address)
    VALUES ('Zeytinli Bahçe', 'Sakin Köşe', ST_GeographyFromText('POINT(26.5 39.5)'), 'Çanakkale, Ayvacık');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM routes LIMIT 1) THEN
    INSERT INTO routes (title, description, path, start_location_name, end_location_name)
    VALUES (
      'Ege Kıyıları Turu',
      'İzmir''den başlayıp Muğla sahillerini gezdiren harika bir rota.',
      ST_GeomFromText('LINESTRING(27.1428 38.4237, 27.3522 37.9483, 27.2736 37.8540, 27.8540 37.3323)'),
      'İzmir', 'Milas'
    );
  END IF;

  IF NOT EXISTS (SELECT 1 FROM seasonal_tips LIMIT 1) THEN
    INSERT INTO seasonal_tips (month, category, title, content) VALUES
      (5, 'Teknik',  'Su Deposu Temizliği',  'Yaz sezonu başlamadan önce su depolarınızı gümüş iyonlu tabletlerle dezenfekte edin.'),
      (5, 'Rota',    'Batı Karadeniz Zamanı','Mayıs ayı, Batı Karadeniz ormanlarının en yeşil olduğu dönemdir.'),
      (5, 'Ekipman', 'Sineklik Kontrolü',    'Havaların ısınmasıyla artan haşerelere karşı sinekliklerinizi kontrol edin.'),
      (6, 'Enerji',  'Panel Isınması',       'Paneller çok ısındığında verim düşer; altındaki hava boşluğu açık olmalı.'),
      (6, 'Kamp',    'Gölge Stratejisi',     'Yazın kapı kuzeye baksın; tente gün boyu gölge sağlar.'),
      (7, 'Güvenlik','Yangın Riski',         'Orman yangını riskinin zirvede olduğu ay; ateş yakmaktan kaçının.'),
      (8, 'Kalabalık','Sahil Yoğunluğu',     'Ağustos sahil yoğunluğu zirvede. İç Anadolu/yayla rotaları daha sakin.'),
      (9, 'Rota',    'Sonbahar Yaylaları',   'Eylül, Karadeniz ve Doğu yaylaları için en uygun ay.'),
      (10,'Bakım',   'Kış Hazırlığı',        'Lastik basıncı, akü voltajı ve antifriz seviyesini kontrol edin.'),
      (11,'Donma',   'Su Hattı Boşaltma',    'İlk donlardan önce kullanılmayan su hatlarını boşaltın.'),
      (12,'Isınma',  'Webasto Bakımı',       'Dizel ısıtıcının yakıt filtresini ve egzoz çıkışını temizleyin.'),
      (1, 'Donma',   'Gri Su Tahliyesi',     'Don riski olan bölgelerde gri su vananızı açık bırakın.'),
      (2, 'Kış Kampı','Termal İzolasyon',    'Pencere termal perdeleri %30 ısı kaybını önler.'),
      (3, 'Bakım',   'Bahar Servisi',        'Yağ + filtre + lastik dönüşümü zamanı.'),
      (4, 'Rota',    'Çiçek Açan Anadolu',   'İç Ege ve Akdeniz hinterlandı kır çiçekleri için en güzel zaman.');
  END IF;
END $$;

-- =====================================================================
-- Storage bucket (görseller için)
-- =====================================================================
INSERT INTO storage.buckets (id, name, public)
VALUES ('karavan_images', 'karavan_images', true)
ON CONFLICT (id) DO NOTHING;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='objects' AND policyname='Public Access') THEN
    EXECUTE $POL$ CREATE POLICY "Public Access" ON storage.objects FOR SELECT USING (bucket_id = 'karavan_images') $POL$;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='objects' AND policyname='Authenticated upload') THEN
    EXECUTE $POL$ CREATE POLICY "Authenticated upload" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'karavan_images' AND auth.role() = 'authenticated') $POL$;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='objects' AND policyname='Owner delete') THEN
    EXECUTE $POL$ CREATE POLICY "Owner delete" ON storage.objects FOR DELETE USING (bucket_id = 'karavan_images' AND auth.uid() = owner) $POL$;
  END IF;
END $$;

-- PostgREST cache yenile
NOTIFY pgrst, 'reload schema';

-- =====================================================================
-- BİTTİ. Şimdi profile auto-create için var olan auth user'ları senkronla:
-- =====================================================================
INSERT INTO public.profiles (id, full_name)
SELECT id, COALESCE(raw_user_meta_data->>'full_name', email)
FROM auth.users
ON CONFLICT (id) DO NOTHING;
