-- Database Schema Part 5 (Bookmarks & UI Enhancements)

CREATE TABLE IF NOT EXISTS bookmarks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  item_type TEXT NOT NULL, -- 'spot', 'post', 'marketplace_item', 'route'
  item_id BIGINT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(user_id, item_type, item_id)
);

ALTER TABLE bookmarks ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own bookmarks" 
ON bookmarks FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Authenticated users can create bookmarks" 
ON bookmarks FOR INSERT WITH CHECK (auth.role() = 'authenticated' AND auth.uid() = user_id);

CREATE POLICY "Users can delete their own bookmarks" 
ON bookmarks FOR DELETE USING (auth.uid() = user_id);

-- 2. Karavan Garaj (Profile Enhancements)
DO $$ 
BEGIN 
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='profiles' AND column_name='battery_capacity') THEN
    ALTER TABLE profiles ADD COLUMN battery_capacity TEXT;
    ALTER TABLE profiles ADD COLUMN solar_panel TEXT;
    ALTER TABLE profiles ADD COLUMN water_tank TEXT;
    ALTER TABLE profiles ADD COLUMN heating_system TEXT;
  END IF;
END $$;

