-- Karavan Komşusu — v21: Social layer (follows, spot reviews, check-ins, DM, maintenance)

-- ────────────────────────────────────────────
-- 1. FOLLOWS
-- ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS follows (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  follower_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  following_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  created_at  TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(follower_id, following_id),
  CHECK (follower_id != following_id)
);

CREATE INDEX IF NOT EXISTS idx_follows_follower  ON follows(follower_id);
CREATE INDEX IF NOT EXISTS idx_follows_following ON follows(following_id);

ALTER TABLE follows ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "follows_read_all"    ON follows;
DROP POLICY IF EXISTS "follows_insert_own"  ON follows;
DROP POLICY IF EXISTS "follows_delete_own"  ON follows;
CREATE POLICY "follows_read_all"   ON follows FOR SELECT USING (true);
CREATE POLICY "follows_insert_own" ON follows FOR INSERT WITH CHECK (auth.uid() = follower_id);
CREATE POLICY "follows_delete_own" ON follows FOR DELETE USING (auth.uid() = follower_id);

-- ────────────────────────────────────────────
-- 2. SPOT REVIEWS (yıldız + yorum)
-- ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS spot_reviews (
  id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id  UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  spot_id  BIGINT NOT NULL,
  rating   INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
  comment  TEXT CHECK (length(comment) <= 500),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(user_id, spot_id)
);

CREATE INDEX IF NOT EXISTS idx_spot_reviews_spot ON spot_reviews(spot_id);

ALTER TABLE spot_reviews ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "spot_reviews_read_all"   ON spot_reviews;
DROP POLICY IF EXISTS "spot_reviews_insert_own" ON spot_reviews;
DROP POLICY IF EXISTS "spot_reviews_update_own" ON spot_reviews;
DROP POLICY IF EXISTS "spot_reviews_delete_own" ON spot_reviews;
CREATE POLICY "spot_reviews_read_all"   ON spot_reviews FOR SELECT USING (true);
CREATE POLICY "spot_reviews_insert_own" ON spot_reviews FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "spot_reviews_update_own" ON spot_reviews FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "spot_reviews_delete_own" ON spot_reviews FOR DELETE USING (auth.uid() = user_id);

-- ────────────────────────────────────────────
-- 3. SPOT CHECK-INS
-- ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS spot_checkins (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id        UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  spot_id        BIGINT NOT NULL,
  checked_in_at  TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(user_id, spot_id)
);

CREATE INDEX IF NOT EXISTS idx_spot_checkins_spot ON spot_checkins(spot_id);

ALTER TABLE spot_checkins ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "checkins_read_all"   ON spot_checkins;
DROP POLICY IF EXISTS "checkins_insert_own" ON spot_checkins;
DROP POLICY IF EXISTS "checkins_delete_own" ON spot_checkins;
CREATE POLICY "checkins_read_all"   ON spot_checkins FOR SELECT USING (true);
CREATE POLICY "checkins_insert_own" ON spot_checkins FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "checkins_delete_own" ON spot_checkins FOR DELETE USING (auth.uid() = user_id);

-- ────────────────────────────────────────────
-- 4. DIRECT MESSAGES
-- ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS direct_messages (
  id          UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  sender_id   UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  receiver_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  content     TEXT NOT NULL CHECK (length(trim(content)) > 0 AND length(content) <= 1000),
  read_at     TIMESTAMP WITH TIME ZONE,
  created_at  TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_dm_sender   ON direct_messages(sender_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_dm_receiver ON direct_messages(receiver_id, created_at DESC);

ALTER TABLE direct_messages ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "dm_read_own"   ON direct_messages;
DROP POLICY IF EXISTS "dm_send_own"   ON direct_messages;
DROP POLICY IF EXISTS "dm_delete_own" ON direct_messages;
CREATE POLICY "dm_read_own"   ON direct_messages FOR SELECT USING (auth.uid() = sender_id OR auth.uid() = receiver_id);
CREATE POLICY "dm_send_own"   ON direct_messages FOR INSERT WITH CHECK (auth.uid() = sender_id);
CREATE POLICY "dm_delete_own" ON direct_messages FOR DELETE USING (auth.uid() = sender_id);

ALTER PUBLICATION supabase_realtime ADD TABLE direct_messages;

-- ────────────────────────────────────────────
-- 5. MAINTENANCE LOGS (bakım takvimi)
-- ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS maintenance_logs (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id       UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  category      TEXT NOT NULL DEFAULT 'Genel',
  title         TEXT NOT NULL,
  date          DATE NOT NULL,
  cost          NUMERIC(10,2),
  odometer_km   INTEGER,
  notes         TEXT,
  next_due_date DATE,
  created_at    TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_maintenance_user ON maintenance_logs(user_id, date DESC);

ALTER TABLE maintenance_logs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "maintenance_read_own"   ON maintenance_logs;
DROP POLICY IF EXISTS "maintenance_insert_own" ON maintenance_logs;
DROP POLICY IF EXISTS "maintenance_update_own" ON maintenance_logs;
DROP POLICY IF EXISTS "maintenance_delete_own" ON maintenance_logs;
CREATE POLICY "maintenance_read_own"   ON maintenance_logs FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "maintenance_insert_own" ON maintenance_logs FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "maintenance_update_own" ON maintenance_logs FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "maintenance_delete_own" ON maintenance_logs FOR DELETE USING (auth.uid() = user_id);
