-- =====================================================================
-- v10 — Events (Etkinlikler & Buluşmalar)
-- - events: Karavancı buluşmaları ve teknik etkinlikler
-- - event_attendees: Etkinliğe katılan kullanıcılar
-- =====================================================================

-- 1. Etkinlikler Tablosu
CREATE TABLE IF NOT EXISTS events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_by UUID REFERENCES profiles(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  location_name TEXT NOT NULL,
  location GEOGRAPHY(POINT),
  event_date TIMESTAMP WITH TIME ZONE NOT NULL,
  category TEXT NOT NULL CHECK (category IN ('Kamp', 'Buluşma', 'Teknik Yardım', 'Atölye', 'Konvoy')),
  image_url TEXT,
  max_participants INTEGER,
  is_verified BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Katılımcılar Tablosu
CREATE TABLE IF NOT EXISTS event_attendees (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id BIGINT REFERENCES events(id) ON DELETE CASCADE,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  joined_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(event_id, user_id)
);

-- 3. RLS Ayarları
ALTER TABLE events ENABLE ROW LEVEL SECURITY;
ALTER TABLE event_attendees ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Events are viewable by everyone" ON events FOR SELECT USING (true);
CREATE POLICY "Auth users can create events" ON events FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Owners can update/delete their events" ON events FOR ALL USING (auth.uid() = created_by);

CREATE POLICY "Attendees are viewable by everyone" ON event_attendees FOR SELECT USING (true);
CREATE POLICY "Auth users can join events" ON event_attendees FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Users can leave events" ON event_attendees FOR DELETE USING (auth.uid() = user_id);

-- 4. XP Tetikleyicisi
CREATE OR REPLACE FUNCTION fn_log_activity_event() RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO activities (user_id, activity_type, description, ref_id)
  VALUES (NEW.created_by, 'note', 'yeni bir etkinlik oluşturdu: ' || NEW.title, NEW.id);
  RETURN NEW;
END $$ LANGUAGE plpgsql;

CREATE TRIGGER trg_activity_event AFTER INSERT ON events FOR EACH ROW EXECUTE FUNCTION fn_log_activity_event();

-- XP Fonksiyonuna Etkinlik Desteği Ekle (v9'daki fonksiyonu güncelle)
-- Zaten 'note' tipi üzerinden XP kazanacak (10 XP). 
-- Ama etkinlik oluşturmaya daha fazla XP verelim.

CREATE OR REPLACE FUNCTION fn_grant_xp() RETURNS TRIGGER AS $$
DECLARE
  xp_to_add INTEGER := 0;
  current_xp INTEGER;
  old_level INTEGER;
  new_level INTEGER;
BEGIN
  -- Activity tipine göre XP belirle
  CASE NEW.activity_type
    WHEN 'post' THEN xp_to_add := 10;
    WHEN 'route' THEN xp_to_add := 25;
    WHEN 'note' THEN 
      IF NEW.description LIKE 'yeni bir etkinlik oluşturdu%' THEN
        xp_to_add := 50;
      ELSE
        xp_to_add := 5;
      END IF;
    WHEN 'item' THEN xp_to_add := 5;
    WHEN 'review' THEN xp_to_add := 15;
    ELSE xp_to_add := 0;
  END CASE;

  -- XP'yi güncelle
  UPDATE profiles SET xp = COALESCE(xp, 0) + xp_to_add WHERE id = NEW.user_id 
  RETURNING xp INTO current_xp;

  -- Seviye atlama kontrolü (Her 100 XP bir seviye)
  old_level := (current_xp - xp_to_add) / 100 + 1;
  new_level := current_xp / 100 + 1;

  IF new_level > old_level THEN
    INSERT INTO activities (user_id, activity_type, description)
    VALUES (NEW.user_id, 'note', 'seviye atladı! Yeni Seviye: ' || new_level);
  END IF;

  RETURN NEW;
END $$ LANGUAGE plpgsql;

NOTIFY pgrst, 'reload schema';
