-- Karavan Komşusu — v19: City stickers / regional badge collection
-- Each Turkish region has a themed sticker. Users earn it on first post/item from that city.

CREATE TABLE IF NOT EXISTS city_stickers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  city_slug TEXT UNIQUE NOT NULL,
  city_name TEXT NOT NULL,
  region TEXT NOT NULL,
  emoji TEXT NOT NULL,
  description TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS user_city_stickers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  sticker_id BIGINT NOT NULL REFERENCES city_stickers(id) ON DELETE CASCADE,
  earned_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(user_id, sticker_id)
);

CREATE INDEX IF NOT EXISTS idx_user_city_stickers_user ON user_city_stickers(user_id);

-- Seed Turkey's iconic regions
INSERT INTO city_stickers (city_slug, city_name, region, emoji, description) VALUES
  ('datca',     'Datça',     'Ege',           '🌰', 'Badem bahçeleri ve mavi koylar'),
  ('bodrum',    'Bodrum',    'Ege',           '⛵', 'Beyaz badanalı evler ve yelkenler'),
  ('cesme',     'Çeşme',     'Ege',           '🏖️', 'Rüzgar ve Egenin altın kıyıları'),
  ('izmir',     'İzmir',     'Ege',           '🌅', 'Gevrek ve Kordon güneşi'),
  ('kazdaglar', 'Kaz Dağları','Marmara',      '🌲', 'Türkiyenin oksijen deposu'),
  ('istanbul',  'İstanbul',  'Marmara',       '🌉', 'İki kıtanın kavşağı'),
  ('canakkale', 'Çanakkale', 'Marmara',       '🐎', 'Truva ve şehitlik diyarı'),
  ('antalya',   'Antalya',   'Akdeniz',       '🌴', 'Toroslar ve mavi sular'),
  ('kas',       'Kaş',       'Akdeniz',       '🐠', 'Antik liman, dalış cenneti'),
  ('olimpos',   'Olimpos',   'Akdeniz',       '🔥', 'Yanan dağ Yanartaş'),
  ('mersin',    'Mersin',    'Akdeniz',       '🍋', 'Limonlu, narlı sahil'),
  ('trabzon',   'Trabzon',   'Karadeniz',     '🐟', 'Hamsi ve Sümela'),
  ('rize',      'Rize',      'Karadeniz',     '🍃', 'Çay bahçeleri ve yeşil'),
  ('artvin',    'Artvin',    'Karadeniz',     '🌧️', 'Yaylalar ve dereler'),
  ('kapadokya', 'Kapadokya', 'İç Anadolu',    '🎈', 'Peri bacaları ve balonlar'),
  ('ankara',    'Ankara',    'İç Anadolu',    '🏛️', 'Başkent, Anıtkabir'),
  ('konya',     'Konya',     'İç Anadolu',    '🕌', 'Mevlana diyarı'),
  ('van',       'Van',       'Doğu Anadolu',  '🐈', 'Van Gölü ve van kedisi'),
  ('erzurum',   'Erzurum',   'Doğu Anadolu',  '⛷️', 'Palandöken karları'),
  ('gaziantep', 'Gaziantep', 'Güneydoğu',     '🥘', 'Mutfak başkenti'),
  ('mardin',    'Mardin',    'Güneydoğu',     '🏰', 'Taş evler, Mezopotamya')
ON CONFLICT (city_slug) DO NOTHING;

-- Helper: extract candidate city slug from a free-text location string
CREATE OR REPLACE FUNCTION match_city_sticker(loc_text TEXT)
RETURNS BIGINT AS $$
DECLARE
  found_id BIGINT;
  needle TEXT;
BEGIN
  IF loc_text IS NULL OR length(trim(loc_text)) = 0 THEN RETURN NULL; END IF;
  needle := lower(unaccent_ish(loc_text));
  SELECT id INTO found_id FROM city_stickers
  WHERE position(city_slug IN needle) > 0
     OR position(lower(unaccent_ish(city_name)) IN needle) > 0
  LIMIT 1;
  RETURN found_id;
END;
$$ LANGUAGE plpgsql;

-- Lightweight Turkish-aware lower (no extension dependency)
CREATE OR REPLACE FUNCTION unaccent_ish(t TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN translate(lower(t),
    'çğıöşüâîû',
    'cgiosuaiu');
END;
$$ LANGUAGE plpgsql IMMUTABLE;

-- Trigger: award sticker on post insert
CREATE OR REPLACE FUNCTION award_city_sticker_post()
RETURNS TRIGGER AS $$
DECLARE
  s_id BIGINT;
BEGIN
  IF NEW.location_name IS NULL THEN RETURN NEW; END IF;
  s_id := match_city_sticker(NEW.location_name);
  IF s_id IS NOT NULL THEN
    INSERT INTO user_city_stickers (user_id, sticker_id)
    VALUES (NEW.user_id, s_id)
    ON CONFLICT (user_id, sticker_id) DO NOTHING;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_award_sticker_post ON posts;
CREATE TRIGGER trg_award_sticker_post
AFTER INSERT ON posts
FOR EACH ROW EXECUTE FUNCTION award_city_sticker_post();

-- Trigger: award sticker on marketplace insert
CREATE OR REPLACE FUNCTION award_city_sticker_item()
RETURNS TRIGGER AS $$
DECLARE
  s_id BIGINT;
BEGIN
  IF NEW.location_name IS NULL THEN RETURN NEW; END IF;
  s_id := match_city_sticker(NEW.location_name);
  IF s_id IS NOT NULL THEN
    INSERT INTO user_city_stickers (user_id, sticker_id)
    VALUES (NEW.user_id, s_id)
    ON CONFLICT (user_id, sticker_id) DO NOTHING;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_award_sticker_item ON marketplace_items;
CREATE TRIGGER trg_award_sticker_item
AFTER INSERT ON marketplace_items
FOR EACH ROW EXECUTE FUNCTION award_city_sticker_item();

-- RLS
ALTER TABLE city_stickers ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_city_stickers ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "city_stickers_read_all" ON city_stickers;
CREATE POLICY "city_stickers_read_all" ON city_stickers FOR SELECT USING (true);

DROP POLICY IF EXISTS "user_city_stickers_read_all" ON user_city_stickers;
CREATE POLICY "user_city_stickers_read_all" ON user_city_stickers FOR SELECT USING (true);

-- Backfill from existing data (one-time)
INSERT INTO user_city_stickers (user_id, sticker_id)
SELECT DISTINCT p.user_id, match_city_sticker(p.location_name)
FROM posts p
WHERE p.user_id IS NOT NULL
  AND match_city_sticker(p.location_name) IS NOT NULL
ON CONFLICT (user_id, sticker_id) DO NOTHING;

INSERT INTO user_city_stickers (user_id, sticker_id)
SELECT DISTINCT m.user_id, match_city_sticker(m.location_name)
FROM marketplace_items m
WHERE m.user_id IS NOT NULL
  AND match_city_sticker(m.location_name) IS NOT NULL
ON CONFLICT (user_id, sticker_id) DO NOTHING;
