-- =====================================================================
-- v9 — Gamification (XP & Achievements)
-- - profiles.xp: Toplam tecrübe puanı
-- - achievements: Rozetlerin ve başarımların tanımı
-- - user_achievements: Kullanıcıların kazandığı rozetler
-- =====================================================================

-- 1. XP kolonunu ekle
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                 WHERE table_name='profiles' AND column_name='xp') THEN
    ALTER TABLE profiles ADD COLUMN xp INTEGER DEFAULT 0;
  END IF;
END $$;

-- 2. Başarımlar tablosu
CREATE TABLE IF NOT EXISTS achievements (
  id TEXT PRIMARY KEY, -- 'first_route', 'social_butterfly', etc.
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  icon TEXT NOT NULL, -- Emoji veya icon adı
  xp_reward INTEGER DEFAULT 0
);

-- 3. Kullanıcı Başarımları
CREATE TABLE IF NOT EXISTS user_achievements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  achievement_id TEXT REFERENCES achievements(id) ON DELETE CASCADE,
  earned_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(user_id, achievement_id)
);

-- 4. Başarım verilerini tohumla
INSERT INTO achievements (id, title, description, icon, xp_reward) VALUES
  ('first_route', 'İlk Yolculuk', 'İlk rotanı başarıyla paylaştın!', '📍', 50),
  ('social_butterfly', 'Sosyal Kelebek', '5 arkadaş edindin!', '🦋', 100),
  ('landscape_master', 'Manzara Ustası', '10 farklı manzara paylaştın!', '📸', 150),
  ('trusted_neighbor', 'Güvenilir Komşu', 'Hesabını doğrulattın!', '🛡️', 200)
ON CONFLICT (id) DO UPDATE SET 
  title = EXCLUDED.title, 
  description = EXCLUDED.description, 
  icon = EXCLUDED.icon, 
  xp_reward = EXCLUDED.xp_reward;

-- 5. Otomatik XP ve Başarım Tetikleyicileri
CREATE OR REPLACE FUNCTION fn_grant_xp() RETURNS TRIGGER AS $$
DECLARE
  xp_to_add INTEGER := 0;
  current_xp INTEGER;
  old_level INTEGER;
  new_level INTEGER;
BEGIN
  -- Activity tipine göre XP belirle
  CASE NEW.activity_type
    WHEN 'post' THEN xp_to_add := 10;
    WHEN 'route' THEN xp_to_add := 25;
    WHEN 'note' THEN xp_to_add := 5;
    WHEN 'item' THEN xp_to_add := 5;
    WHEN 'review' THEN xp_to_add := 15;
    ELSE xp_to_add := 0;
  END CASE;

  -- XP'yi güncelle
  UPDATE profiles SET xp = COALESCE(xp, 0) + xp_to_add WHERE id = NEW.user_id 
  RETURNING xp INTO current_xp;

  -- Seviye atlama kontrolü (Her 100 XP bir seviye)
  old_level := (current_xp - xp_to_add) / 100 + 1;
  new_level := current_xp / 100 + 1;

  IF new_level > old_level THEN
    -- Seviye atlama aktivitesi logla
    INSERT INTO activities (user_id, activity_type, description)
    VALUES (NEW.user_id, 'note', 'seviye atladı! Yeni Seviye: ' || new_level);
  END IF;

  RETURN NEW;
END $$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_grant_xp ON activities;
CREATE TRIGGER trg_grant_xp AFTER INSERT ON activities FOR EACH ROW EXECUTE FUNCTION fn_grant_xp();

-- 6. Belirli başarımları kontrol eden fonksiyonlar
CREATE OR REPLACE FUNCTION check_achievements() RETURNS TRIGGER AS $$
DECLARE
  route_count INTEGER;
  friend_count INTEGER;
  post_count INTEGER;
  is_verified_user BOOLEAN;
BEGIN
  -- Rota Sayısı
  SELECT count(*) INTO route_count FROM routes WHERE user_id = NEW.id;
  IF route_count >= 1 THEN
    INSERT INTO user_achievements (user_id, achievement_id) VALUES (NEW.id, 'first_route') ON CONFLICT DO NOTHING;
  END IF;

  -- Arkadaş Sayısı
  SELECT count(*) INTO friend_count FROM friendships WHERE (user_id = NEW.id OR friend_id = NEW.id) AND status = 'accepted';
  IF friend_count >= 5 THEN
    INSERT INTO user_achievements (user_id, achievement_id) VALUES (NEW.id, 'social_butterfly') ON CONFLICT DO NOTHING;
  END IF;

  -- Manzara Sayısı
  SELECT count(*) INTO post_count FROM posts WHERE user_id = NEW.id;
  IF post_count >= 10 THEN
    INSERT INTO user_achievements (user_id, achievement_id) VALUES (NEW.id, 'landscape_master') ON CONFLICT DO NOTHING;
  END IF;

  -- Doğrulanmış üye
  IF NEW.is_verified THEN
    INSERT INTO user_achievements (user_id, achievement_id) VALUES (NEW.id, 'trusted_neighbor') ON CONFLICT DO NOTHING;
  END IF;

  RETURN NEW;
END $$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_check_achievements ON profiles;
CREATE TRIGGER trg_check_achievements AFTER UPDATE OF is_verified ON profiles FOR EACH ROW EXECUTE FUNCTION check_achievements();

-- İlk başta da çalışması için INSERT tetikleyicisi (gerekiyorsa)
-- Şimdilik update üzerinde yoğunlaşalım.

NOTIFY pgrst, 'reload schema';
