-- =====================================================================
-- v12 — Community Challenges (Haftalık Görevler)
-- - challenges: Global görevler
-- - user_challenges: Kullanıcıların görev ilerlemeleri
-- =====================================================================

-- 1. Görevler Tablosu
CREATE TABLE IF NOT EXISTS challenges (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  xp_reward INTEGER DEFAULT 50,
  icon TEXT DEFAULT '🏆',
  category TEXT NOT NULL CHECK (category IN ('Mekanik', 'Manzara', 'Sosyal', 'Rota')),
  starts_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  ends_at TIMESTAMP WITH TIME ZONE DEFAULT (now() + interval '7 days')
);

-- 2. Kullanıcı Görev İlerlemeleri
CREATE TABLE IF NOT EXISTS user_challenges (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  challenge_id BIGINT REFERENCES challenges(id) ON DELETE CASCADE,
  status TEXT DEFAULT 'active' CHECK (status IN ('active', 'completed')),
  completed_at TIMESTAMP WITH TIME ZONE,
  UNIQUE(user_id, challenge_id)
);

-- 3. Tohum Veriler (Örnek Görevler)
INSERT INTO challenges (title, description, xp_reward, icon, category) VALUES
  ('Güneş Avcısı', 'Bu hafta 3 farklı konumda manzara paylaş.', 100, '☀️', 'Manzara'),
  ('Yardım Eli', 'Telsizden bir soruya cevap ver veya SOS''e git.', 150, '🛠️', 'Mekanik'),
  ('Rota Kaşifi', 'İlk kez gidilen bir rotada iz bırak.', 120, '📍', 'Rota'),
  ('Kamp Ateşi Dostluğu', 'Bir etkinliğe katıl ve 2 yeni arkadaş ekle.', 200, '🔥', 'Sosyal')
ON CONFLICT DO NOTHING;

-- 4. RLS
ALTER TABLE challenges ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_challenges ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Challenges are viewable by everyone" ON challenges FOR SELECT USING (true);
CREATE POLICY "User challenges are viewable by owner" ON user_challenges FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can update their challenges" ON user_challenges FOR UPDATE USING (auth.uid() = user_id);

-- 5. Görev Tamamlama Fonksiyonu (XP Tetikleyici ile entegre)
CREATE OR REPLACE FUNCTION complete_challenge(p_user_id UUID, p_challenge_id BIGINT) RETURNS VOID AS $$
DECLARE
  v_xp INTEGER;
BEGIN
  -- Görevi tamamla
  UPDATE user_challenges 
  SET status = 'completed', completed_at = now() 
  WHERE user_id = p_user_id AND challenge_id = p_challenge_id AND status = 'active';

  IF FOUND THEN
    SELECT xp_reward INTO v_xp FROM challenges WHERE id = p_challenge_id;
    
    -- XP aktivitesi logla (fn_grant_xp bunu otomatik işleyecek)
    INSERT INTO activities (user_id, activity_type, description)
    VALUES (p_user_id, 'note', 'bir görevi tamamladı: ' || (SELECT title FROM challenges WHERE id = p_challenge_id));
    
    -- Not: fn_grant_xp'ye bu özel 'note' tipi için yüksek puan kuralı ekleyebiliriz veya direkt profiles'ı güncelleyebiliriz.
    -- Şimdilik fn_grant_xp'yi güncelleyelim.
  END IF;
END;
$$ LANGUAGE plpgsql;

NOTIFY pgrst, 'reload schema';
