-- Database Schema for Karavan Komşusu
CREATE EXTENSION IF NOT EXISTS postgis;


-- 1. Profiles (Kullanıcı Günlükleri)
CREATE TABLE profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  username TEXT UNIQUE,
  full_name TEXT,
  avatar_url TEXT,
  caravan_type TEXT, -- 'Çekme Karavan', 'Motokaravan', 'Van', etc.
  bio TEXT,
  location_visible BOOLEAN DEFAULT true,
  last_location GEOGRAPHY(POINT),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Sakin Köşeler (Konaklama Noktaları)
CREATE TABLE spots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_by UUID REFERENCES profiles(id),
  title TEXT NOT NULL,
  description TEXT,
  category TEXT, -- 'Ücretsiz', 'İşletme', 'Çiftlik'
  location GEOGRAPHY(POINT) NOT NULL,
  address TEXT,
  features JSONB, -- {water: true, electricity: false, wifi: true}
  images TEXT[], -- Array of URLs
  is_verified BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Yol Yardımcıları (Ustalar)
CREATE TABLE service_providers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  category TEXT NOT NULL, -- 'Elektrik', 'Marangoz', 'Mekanik', 'Güneş Paneli'
  phone TEXT,
  whatsapp TEXT,
  address TEXT,
  location GEOGRAPHY(POINT),
  images TEXT[],
  rating DECIMAL DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. İzlenimler (Yorumlar)
CREATE TABLE reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES profiles(id),
  spot_id BIGINT REFERENCES spots(id),
  service_id BIGINT REFERENCES service_providers(id),
  rating INTEGER CHECK (rating >= 1 AND rating <= 5),
  comment TEXT,
  images TEXT[],
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. Yol Arkadaşları (Takipleşme)
CREATE TABLE friendships (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES profiles(id),
  friend_id UUID REFERENCES profiles(id),
  status TEXT DEFAULT 'pending', -- 'pending', 'accepted'
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(user_id, friend_id)
);
