-- Database Schema Part 4 (Telsiz & Social Fixes)

-- 9. Telsiz (Messages)
CREATE TABLE IF NOT EXISTS messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  channel TEXT NOT NULL, -- 'Kamp 1', 'dm_user1_user2', etc.
  text TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS for messages
ALTER TABLE messages ENABLE ROW LEVEL SECURITY;

-- Policies for messages
CREATE POLICY "Messages are viewable by everyone" 
ON messages FOR SELECT USING (true);

CREATE POLICY "Authenticated users can insert messages" 
ON messages FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- 10. Askıda Not (Geographic Notes)
CREATE TABLE IF NOT EXISTS geographic_notes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  note TEXT NOT NULL,
  location GEOGRAPHY(POINT) NOT NULL,
  location_name TEXT,
  expires_at TIMESTAMP WITH TIME ZONE DEFAULT (now() + interval '7 days'),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE geographic_notes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Notes are viewable by everyone" 
ON geographic_notes FOR SELECT USING (true);

CREATE POLICY "Authenticated users can insert notes" 
ON geographic_notes FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- 11. İz Bırak (Routes)
DROP VIEW IF EXISTS vw_routes;
DROP TABLE IF EXISTS routes CASCADE;

CREATE TABLE routes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT,
  path GEOGRAPHY(LINESTRING) NOT NULL,
  start_location_name TEXT,
  end_location_name TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE routes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Routes are viewable by everyone" 
ON routes FOR SELECT USING (true);

CREATE POLICY "Authenticated users can insert routes" 
ON routes FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- 12. View for Geographic Notes
CREATE OR REPLACE VIEW vw_geographic_notes AS
SELECT 
  id, user_id, note, location_name, created_at,
  ST_Y(location::geometry) as lat, 
  ST_X(location::geometry) as lng 
FROM geographic_notes;
DO $$ 
BEGIN 
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='profiles' AND column_name='caravan_type') THEN
    ALTER TABLE profiles ADD COLUMN caravan_type TEXT;
  END IF;
END $$;

-- 13. View for Routes
CREATE OR REPLACE VIEW vw_routes AS
SELECT 
  id, user_id, title, description, start_location_name, end_location_name, created_at,
  ST_AsGeoJSON(path)::json as geojson_path
FROM routes;

-- Dummy Data for testing Routes
INSERT INTO routes (title, description, path, start_location_name, end_location_name)
VALUES (
  'Ege Kıyıları Turu', 
  'İzmir''den başlayıp Muğla sahillerini gezdiren harika bir rota.',
  ST_GeomFromText('LINESTRING(27.1428 38.4237, 27.3522 37.9483, 27.2736 37.8540, 27.8540 37.3323)'),
  'İzmir',
  'Milas'
) ;
