-- =====================================================================
-- Karavan Komşusu — FULL PRODUCTION SCHEMA (v1 - v16 Consolidated)
-- =====================================================================

-- 1. EXTENSIONS
CREATE EXTENSION IF NOT EXISTS postgis;

-- 2. TABLES
CREATE TABLE IF NOT EXISTS profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  full_name TEXT,
  username TEXT UNIQUE,
  avatar_url TEXT,
  caravan_type TEXT,
  battery_capacity TEXT,
  solar_panel TEXT,
  water_tank TEXT,
  heating_system TEXT,
  xp INTEGER DEFAULT 0,
  share_location BOOLEAN DEFAULT false,
  last_location GEOGRAPHY(POINT),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  caption TEXT,
  image_url TEXT,
  location_name TEXT,
  likes_count INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id BIGINT REFERENCES posts(id) ON DELETE CASCADE,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  comment TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  channel TEXT NOT NULL,
  text TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS geographic_notes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  note TEXT NOT NULL,
  location GEOGRAPHY(POINT) NOT NULL,
  location_name TEXT,
  expires_at TIMESTAMP WITH TIME ZONE DEFAULT (now() + interval '7 days'),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS routes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT,
  path GEOGRAPHY(LINESTRING) NOT NULL,
  start_location_name TEXT,
  end_location_name TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS spots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  category TEXT NOT NULL,
  location GEOGRAPHY(POINT) NOT NULL,
  address TEXT,
  image_url TEXT,
  attributes JSONB DEFAULT '{}'::jsonb,
  created_by UUID REFERENCES profiles(id) ON DELETE SET NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  creator_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT,
  location_name TEXT,
  event_date TIMESTAMP WITH TIME ZONE NOT NULL,
  category TEXT CHECK (category IN ('Buluşma', 'Konvoy', 'Teknik Atölye', 'Eğlence')),
  max_participants INTEGER DEFAULT 20,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS event_attendees (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id BIGINT REFERENCES events(id) ON DELETE CASCADE,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(event_id, user_id)
);

CREATE TABLE IF NOT EXISTS activities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  activity_type TEXT NOT NULL, -- 'post', 'route', 'spot', 'event', 'note'
  description TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS daily_checkins (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  checkin_date DATE DEFAULT CURRENT_DATE,
  UNIQUE(user_id, checkin_date)
);

CREATE TABLE IF NOT EXISTS challenges (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  xp_reward INTEGER DEFAULT 50,
  icon TEXT DEFAULT '🏆',
  category TEXT NOT NULL,
  starts_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  ends_at TIMESTAMP WITH TIME ZONE DEFAULT (now() + interval '7 days')
);

CREATE TABLE IF NOT EXISTS user_challenges (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  challenge_id BIGINT REFERENCES challenges(id) ON DELETE CASCADE,
  status TEXT DEFAULT 'active',
  completed_at TIMESTAMP WITH TIME ZONE,
  UNIQUE(user_id, challenge_id)
);

-- 3. VIEWS
CREATE OR REPLACE VIEW vw_spots AS
SELECT 
  id, title, description, category, address, image_url, attributes, created_by,
  ST_Y(location::geometry) as lat, 
  ST_X(location::geometry) as lng 
FROM spots;

CREATE OR REPLACE VIEW vw_geographic_notes AS
SELECT 
  gn.id, gn.user_id, gn.note, gn.location_name, gn.created_at,
  p.full_name as profile_full_name,
  ST_Y(gn.location::geometry) as lat, 
  ST_X(gn.location::geometry) as lng 
FROM geographic_notes gn
LEFT JOIN profiles p ON gn.user_id = p.id;

CREATE OR REPLACE VIEW vw_routes AS
SELECT 
  r.id, r.user_id, r.title, r.description, r.start_location_name, r.end_location_name, r.created_at,
  p.full_name as profile_full_name,
  ST_AsGeoJSON(r.path)::json as geojson_path
FROM routes r
LEFT JOIN profiles p ON r.user_id = p.id;

-- 4. FUNCTIONS & TRIGGERS (XP System)
CREATE OR REPLACE FUNCTION fn_grant_xp() RETURNS TRIGGER AS $$
DECLARE
  xp_to_add INTEGER := 0;
BEGIN
  CASE NEW.activity_type
    WHEN 'post' THEN xp_to_add := 20;
    WHEN 'route' THEN xp_to_add := 30;
    WHEN 'spot' THEN xp_to_add := 50;
    WHEN 'event' THEN xp_to_add := 40;
    WHEN 'note' THEN 
      IF NEW.description LIKE 'yeni bir etkinlik oluşturdu%' THEN xp_to_add := 50;
      ELSIF NEW.description LIKE 'etkinliğe katıldı%' THEN xp_to_add := 10;
      ELSIF NEW.description LIKE 'bir görevi tamamladı%' THEN xp_to_add := 100;
      ELSIF NEW.description = 'günlük giriş ödülü' THEN xp_to_add := 5;
      ELSE xp_to_add := 5;
      END IF;
  END CASE;

  UPDATE profiles SET xp = xp + xp_to_add WHERE id = NEW.user_id;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER tr_grant_xp AFTER INSERT ON activities
FOR EACH ROW EXECUTE FUNCTION fn_grant_xp();

-- 5. RPC FUNCTIONS
CREATE OR REPLACE FUNCTION check_in_user(p_user_id UUID) RETURNS BOOLEAN AS $$
BEGIN
  INSERT INTO daily_checkins (user_id) VALUES (p_user_id);
  INSERT INTO activities (user_id, activity_type, description) VALUES (p_user_id, 'note', 'günlük giriş ödülü');
  RETURN TRUE;
EXCEPTION WHEN OTHERS THEN
  RETURN FALSE;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION complete_challenge(p_user_id UUID, p_challenge_id BIGINT) RETURNS VOID AS $$
BEGIN
  UPDATE user_challenges SET status = 'completed', completed_at = now() 
  WHERE user_id = p_user_id AND challenge_id = p_challenge_id AND status = 'active';
  IF FOUND THEN
    INSERT INTO activities (user_id, activity_type, description)
    VALUES (p_user_id, 'note', 'bir görevi tamamladı: ' || (SELECT title FROM challenges WHERE id = p_challenge_id));
  END IF;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION get_nearby_neighbors(p_user_id UUID, p_lat DOUBLE PRECISION, p_lng DOUBLE PRECISION, p_radius_km DOUBLE PRECISION) 
RETURNS TABLE (id UUID, full_name TEXT, caravan_type TEXT, avatar_url TEXT, distance_km DOUBLE PRECISION) AS $$
BEGIN
  RETURN QUERY SELECT p.id, p.full_name, p.caravan_type, p.avatar_url,
    ST_Distance(p.last_location, ST_SetSRID(ST_MakePoint(p_lng, p_lat), 4326)::geography) / 1000
  FROM profiles p WHERE p.id != p_user_id AND p.share_location = true 
  AND ST_DWithin(p.last_location, ST_SetSRID(ST_MakePoint(p_lng, p_lat), 4326)::geography, p_radius_km * 1000)
  ORDER BY 5 ASC;
END;
$$ LANGUAGE plpgsql;

-- 6. DUMMY CHALLENGES
INSERT INTO challenges (title, description, xp_reward, icon, category) VALUES
  ('Güneş Avcısı', 'Bu hafta 3 farklı konumda manzara paylaş.', 100, '☀️', 'Manzara'),
  ('Yardım Eli', 'Telsizden bir soruya cevap ver veya SOS''e git.', 150, '🛠️', 'Mekanik')
ON CONFLICT DO NOTHING;

-- 7. RLS (Production Mode - Minimal policies for public views)
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public profiles are viewable by everyone" ON profiles FOR SELECT USING (true);
CREATE POLICY "Users can update own profile" ON profiles FOR UPDATE USING (auth.uid() = id);

-- NOTIFY PostgREST to reload
NOTIFY pgrst, 'reload schema';
